//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.08 at 09:52:08 AM PST 
//


package com.wordnik.examples.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for frequencySummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="frequencySummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}frequency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="totalCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="unknownYearCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="wordId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "frequencySummary", propOrder = {
    "frequency",
    "totalCount",
    "unknownYearCount",
    "wordId"
})
public class FrequencySummary {

    protected List<FrequencyValue> frequency;
    protected long totalCount;
    protected int unknownYearCount;
    protected long wordId;

    /**
     * Gets the value of the frequency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frequency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrequency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FrequencyValue }
     * 
     * 
     */
    public List<FrequencyValue> getFrequency() {
        if (frequency == null) {
            frequency = new ArrayList<FrequencyValue>();
        }
        return this.frequency;
    }

    /**
     * Gets the value of the totalCount property.
     * 
     */
    public long getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the value of the totalCount property.
     * 
     */
    public void setTotalCount(long value) {
        this.totalCount = value;
    }

    /**
     * Gets the value of the unknownYearCount property.
     * 
     */
    public int getUnknownYearCount() {
        return unknownYearCount;
    }

    /**
     * Sets the value of the unknownYearCount property.
     * 
     */
    public void setUnknownYearCount(int value) {
        this.unknownYearCount = value;
    }

    /**
     * Gets the value of the wordId property.
     * 
     */
    public long getWordId() {
        return wordId;
    }

    /**
     * Sets the value of the wordId property.
     * 
     */
    public void setWordId(long value) {
        this.wordId = value;
    }

}
