//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.24 at 08:58:29 PM PDT 
//


package com.wordnik.examples.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for wordListWord complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wordListWord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="numberCommentsOnWord" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="numberLists" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wordstring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wordListWord", propOrder = {
    "createdAt",
    "numberCommentsOnWord",
    "numberLists",
    "userId",
    "userName",
    "wordstring"
})
public class WordListWord {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdAt;
    protected long numberCommentsOnWord;
    protected long numberLists;
    protected long userId;
    protected String userName;
    protected String wordstring;

    /**
     * Gets the value of the createdAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedAt(XMLGregorianCalendar value) {
        this.createdAt = value;
    }

    /**
     * Gets the value of the numberCommentsOnWord property.
     * 
     */
    public long getNumberCommentsOnWord() {
        return numberCommentsOnWord;
    }

    /**
     * Sets the value of the numberCommentsOnWord property.
     * 
     */
    public void setNumberCommentsOnWord(long value) {
        this.numberCommentsOnWord = value;
    }

    /**
     * Gets the value of the numberLists property.
     * 
     */
    public long getNumberLists() {
        return numberLists;
    }

    /**
     * Sets the value of the numberLists property.
     * 
     */
    public void setNumberLists(long value) {
        this.numberLists = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     */
    public void setUserId(long value) {
        this.userId = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the wordstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordstring() {
        return wordstring;
    }

    /**
     * Sets the value of the wordstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordstring(String value) {
        this.wordstring = value;
    }

}
