//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.08 at 09:54:07 AM PST 
//


package com.wordnik.examples.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for word complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="word">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="vulgar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wordstring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "word", propOrder = {
    "id",
    "vulgar",
    "wordstring"
})
public class Word {

    protected long id;
    protected String vulgar;
    protected String wordstring;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the vulgar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVulgar() {
        return vulgar;
    }

    /**
     * Sets the value of the vulgar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVulgar(String value) {
        this.vulgar = value;
    }

    /**
     * Gets the value of the wordstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWordstring() {
        return wordstring;
    }

    /**
     * Sets the value of the wordstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWordstring(String value) {
        this.wordstring = value;
    }

}
